# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"\"\n\x0e\x43onnectRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"3\n\x0f\x43onnectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\x0eMessageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"3\n\x0fMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x12GetMessagesRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"b\n\x0b\x43hatMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x0f\n\x07message\x18\x05 \x01(\t\"\x12\n\x10ListUsersRequest\"*\n\x08UserList\x12\r\n\x05users\x18\x01 \x03(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"%\n\x11\x44isconnectRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"6\n\x12\x44isconnectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb5\x02\n\x0b\x43hatService\x12\x36\n\x07\x43onnect\x12\x14.chat.ConnectRequest\x1a\x15.chat.ConnectResponse\x12:\n\x0bSendMessage\x12\x14.chat.MessageRequest\x1a\x15.chat.MessageResponse\x12<\n\x0bGetMessages\x12\x18.chat.GetMessagesRequest\x1a\x11.chat.ChatMessage0\x01\x12\x33\n\tListUsers\x12\x16.chat.ListUsersRequest\x1a\x0e.chat.UserList\x12?\n\nDisconnect\x12\x17.chat.DisconnectRequest\x1a\x18.chat.DisconnectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNECTREQUEST']._serialized_start=20
  _globals['_CONNECTREQUEST']._serialized_end=54
  _globals['_CONNECTRESPONSE']._serialized_start=56
  _globals['_CONNECTRESPONSE']._serialized_end=107
  _globals['_MESSAGEREQUEST']._serialized_start=109
  _globals['_MESSAGEREQUEST']._serialized_end=157
  _globals['_MESSAGERESPONSE']._serialized_start=159
  _globals['_MESSAGERESPONSE']._serialized_end=210
  _globals['_GETMESSAGESREQUEST']._serialized_start=212
  _globals['_GETMESSAGESREQUEST']._serialized_end=250
  _globals['_CHATMESSAGE']._serialized_start=252
  _globals['_CHATMESSAGE']._serialized_end=350
  _globals['_LISTUSERSREQUEST']._serialized_start=352
  _globals['_LISTUSERSREQUEST']._serialized_end=370
  _globals['_USERLIST']._serialized_start=372
  _globals['_USERLIST']._serialized_end=414
  _globals['_DISCONNECTREQUEST']._serialized_start=416
  _globals['_DISCONNECTREQUEST']._serialized_end=453
  _globals['_DISCONNECTRESPONSE']._serialized_start=455
  _globals['_DISCONNECTRESPONSE']._serialized_end=509
  _globals['_CHATSERVICE']._serialized_start=512
  _globals['_CHATSERVICE']._serialized_end=821
# @@protoc_insertion_point(module_scope)
