# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import naming_service_pb2 as naming__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in naming_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NamingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterServer = channel.unary_unary(
                '/naming_service.NamingService/RegisterServer',
                request_serializer=naming__service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=naming__service__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/naming_service.NamingService/Heartbeat',
                request_serializer=naming__service__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=naming__service__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.LookupServer = channel.unary_unary(
                '/naming_service.NamingService/LookupServer',
                request_serializer=naming__service__pb2.LookupRequest.SerializeToString,
                response_deserializer=naming__service__pb2.LookupResponse.FromString,
                _registered_method=True)
        self.ListServers = channel.unary_unary(
                '/naming_service.NamingService/ListServers',
                request_serializer=naming__service__pb2.ListServersRequest.SerializeToString,
                response_deserializer=naming__service__pb2.ListServersResponse.FromString,
                _registered_method=True)


class NamingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NamingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterServer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterServer,
                    request_deserializer=naming__service__pb2.RegisterRequest.FromString,
                    response_serializer=naming__service__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=naming__service__pb2.HeartbeatRequest.FromString,
                    response_serializer=naming__service__pb2.HeartbeatResponse.SerializeToString,
            ),
            'LookupServer': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupServer,
                    request_deserializer=naming__service__pb2.LookupRequest.FromString,
                    response_serializer=naming__service__pb2.LookupResponse.SerializeToString,
            ),
            'ListServers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServers,
                    request_deserializer=naming__service__pb2.ListServersRequest.FromString,
                    response_serializer=naming__service__pb2.ListServersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'naming_service.NamingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('naming_service.NamingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NamingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naming_service.NamingService/RegisterServer',
            naming__service__pb2.RegisterRequest.SerializeToString,
            naming__service__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naming_service.NamingService/Heartbeat',
            naming__service__pb2.HeartbeatRequest.SerializeToString,
            naming__service__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naming_service.NamingService/LookupServer',
            naming__service__pb2.LookupRequest.SerializeToString,
            naming__service__pb2.LookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naming_service.NamingService/ListServers',
            naming__service__pb2.ListServersRequest.SerializeToString,
            naming__service__pb2.ListServersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
