# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: naming_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'naming_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14naming_service.proto\x12\x0enaming_service\"I\n\x0fRegisterRequest\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x12\n\nis_primary\x18\x03 \x01(\x08\"#\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"%\n\x10HeartbeatRequest\x12\x11\n\tserver_id\x18\x01 \x01(\t\"$\n\x11HeartbeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x0f\n\rLookupRequest\"E\n\x0eLookupResponse\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\"\x14\n\x12ListServersRequest\"B\n\x13ListServersResponse\x12+\n\x07servers\x18\x01 \x03(\x0b\x32\x1a.naming_service.ServerInfo\"l\n\nServerInfo\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x12\n\nis_primary\x18\x03 \x01(\x08\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x16\n\x0elast_heartbeat\x18\x05 \x01(\t2\xdd\x02\n\rNamingService\x12S\n\x0eRegisterServer\x12\x1f.naming_service.RegisterRequest\x1a .naming_service.RegisterResponse\x12P\n\tHeartbeat\x12 .naming_service.HeartbeatRequest\x1a!.naming_service.HeartbeatResponse\x12M\n\x0cLookupServer\x12\x1d.naming_service.LookupRequest\x1a\x1e.naming_service.LookupResponse\x12V\n\x0bListServers\x12\".naming_service.ListServersRequest\x1a#.naming_service.ListServersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'naming_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=40
  _globals['_REGISTERREQUEST']._serialized_end=113
  _globals['_REGISTERRESPONSE']._serialized_start=115
  _globals['_REGISTERRESPONSE']._serialized_end=150
  _globals['_HEARTBEATREQUEST']._serialized_start=152
  _globals['_HEARTBEATREQUEST']._serialized_end=189
  _globals['_HEARTBEATRESPONSE']._serialized_start=191
  _globals['_HEARTBEATRESPONSE']._serialized_end=227
  _globals['_LOOKUPREQUEST']._serialized_start=229
  _globals['_LOOKUPREQUEST']._serialized_end=244
  _globals['_LOOKUPRESPONSE']._serialized_start=246
  _globals['_LOOKUPRESPONSE']._serialized_end=315
  _globals['_LISTSERVERSREQUEST']._serialized_start=317
  _globals['_LISTSERVERSREQUEST']._serialized_end=337
  _globals['_LISTSERVERSRESPONSE']._serialized_start=339
  _globals['_LISTSERVERSRESPONSE']._serialized_end=405
  _globals['_SERVERINFO']._serialized_start=407
  _globals['_SERVERINFO']._serialized_end=515
  _globals['_NAMINGSERVICE']._serialized_start=518
  _globals['_NAMINGSERVICE']._serialized_end=867
# @@protoc_insertion_point(module_scope)
